config/routes.rb
Rails.application.routes.draw do

  root                'static_pages#home'
  #get    'home'    => 'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
        if logged_in?
            @micropost  = current_user.microposts.build
            @feed_items = current_user.feed.paginate(page: params[:page])
        end
    end

    def help
    end

    def about
    end

    def contact
    end

    def development
        render layout: 'construction'
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p class="text-center">
  Post It is my implementation of Twitter like website with the nominal features. I hope you enjoy using it
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Me</h1>
<p class="text-center">
  Designed and Developed by Arvind Rachuri | 2015IPG013 | ari0997@gmail.com
</p>

app/views/static_pages/development.html.erb
<div class="dialog">
  <div>
    <h1>Thank you folks!</h1>
  </div>
  <p>The site has been pulled down and has gone into development phase! We will get it up and running ASAP</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Any suggestion, query, bug reports, security issues etc. are most welcome! This is Beta Version of the App!
  Please send all the feedback to ari0997@gmail.com. Thanks!
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
        <section class="micropost_form">
          <%= render 'shared/micropost_form' %>
        </section>
      </aside>
      <div class="col-md-8">
        <h3>MicroPost Feed</h3>
        <%= render 'shared/feed' %>
      </div>
    </div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to Post It</h1>

  <h2>
    A small scale implementation of Twitter
  </h2>
  <% if !logged_in? %>
  <%= link_to "Sign up now!", signup_url, class: "btn btn-lg btn-primary" %>
  <%end%>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
<% end %>